version: '3.9'

services:
  db:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5431"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-microservices-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - app-data:/data
    environment:
      SPRING_BOOT_POSTGRES_DB: jdbc:postgresql://db:5431/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  app-data:
    driver: local