CREATE ROLE client;
CREATE ROLE employee;
CREATE ROLE admin;
CREATE ROLE manager
CREATE ROLE guest;
CREATE ROLE 'customer support';

GRANT ALL PRIVILEGES ON DATABASE user_services TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE clients TO client;